### ISSUE TITLE
problem with id create

### ISSUE THREAD

**Issue by ZhangTao1596** [bitdust-io/public#11]
1. I install bitdust following the steps in readme
2. but when i use 
`bitdust id create tom`,
got this:
` INFO Active network is [main]   identity_servers={b'p2p-id.ru': (80, 6661), b'p2p-alice.ai': (80, 6661), b'bitdust.ai': (80, 6661), b'bitrex.ai': (80, 6661), b'new-vennep.ai': (80, 6661), b'seed.bitdust.io': (80, 6661)}  in known_servers.default_nodes()`
I dont know what to do next.

**Comment by vesellov** [comment]
Hi Tom!  Did you saw the message: `+ new user tom registered successfully!` ? 
If not, try again... Identity create process sometimes failing when software is not able to detect your external IP address... this depends on your network configuration.  so in this situation you can just retry and if identity already created it will print you :
```
bitdust id create veselin8
local identity [veselin8] already exist
```

Then you just run directly in your terminal :
```
bitdust
```

**Comment by vesellov** [comment]
@KickSeason ...

If this is still failing you can check it in a different way...   We need to know if BitDust will be able to run actually on your machine with your current internet connection...

First run BitDust in background (you do not need identity to start BitDust software, but you need identity to be able to talk to other people) : 

```
bitdust daemon
new BitDust process will be started in daemon mode, finishing current process
```

Then try to see if "stun my external IP" method is working actually for you :

```
bitdust api network_stun
{ u'execution': u'7.129433',
  u'result': [ { u'details': 8489,
                 u'ip': u'123.45.67.89',
                 u'result': u'stun-success',
                 u'type': u'non-symmetric'}],
  u'status': u'OK'}
```

if this is OK, then it must be some another error during identity create process....

**Comment by ZhangTao1596** [comment]
thank you. I'll try.

**Comment by vesellov** [comment]
this issue suppose to be resolved now
